server:
  port: 8030

spring:
  application:
    name: ai-demo
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  ai:
    openai:
      api-key: API_KEY
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2